import { Adjuster, ResolvedCase, Quote, ChatRoom, Message } from '../types';

export const mockAdjusters: Adjuster[] = [
  {
    id: '1',
    email: 'kim@adjuster.com',
    name: '김민준',
    userType: 'adjuster',
    phone: '010-1234-5678',
    licenseNumber: 'ADJ-2019-0042',
    specialties: ['교통사고', '상해사고'],
    rating: 4.9,
    reviewCount: 127,
    resolvedCases: 312,
    bio: '10년 경력의 전문 손해사정사. 교통사고 전문.',
    fee: '성공 보수 15%',
    createdAt: '2019-01-01',
  },
  {
    id: '2',
    email: 'lee@adjuster.com',
    name: '이서연',
    userType: 'adjuster',
    phone: '010-2345-6789',
    licenseNumber: 'ADJ-2017-0018',
    specialties: ['화재사고', '재산피해'],
    rating: 4.8,
    reviewCount: 89,
    resolvedCases: 245,
    bio: '화재·재산 피해 전문. 보험사 출신 15년 경력.',
    fee: '성공 보수 12%',
    createdAt: '2017-01-01',
  },
  {
    id: '3',
    email: 'park@adjuster.com',
    name: '박지호',
    userType: 'adjuster',
    phone: '010-3456-7890',
    licenseNumber: 'ADJ-2021-0093',
    specialties: ['의료사고', '산업재해'],
    rating: 4.7,
    reviewCount: 54,
    resolvedCases: 128,
    bio: '의료·산재 사고 전문. 의대 출신 손해사정사.',
    fee: '성공 보수 18%',
    createdAt: '2021-01-01',
  },
];

export const mockResolvedCases: ResolvedCase[] = [
  {
    id: '1',
    title: '음주운전 피해 보상 극대화',
    category: '교통사고',
    originalAmount: '1,200만원',
    resolvedAmount: '4,800만원',
    description: '보험사 최초 제시액 대비 4배 보상 성공. 후유장해 항목 추가 청구.',
    adjusterName: '김민준',
    resolvedAt: '2025-12-10',
  },
  {
    id: '2',
    title: '아파트 누수 피해 보상',
    category: '재산피해',
    originalAmount: '500만원',
    resolvedAmount: '1,850만원',
    description: '인테리어 피해 및 이사비용 포함 추가 항목 성공적으로 청구.',
    adjusterName: '이서연',
    resolvedAt: '2026-01-22',
  },
  {
    id: '3',
    title: '수술 후 합병증 의료사고',
    category: '의료사고',
    originalAmount: '800만원',
    resolvedAmount: '3,200만원',
    description: '일실수입 및 향후치료비 포함 전액 보상 달성.',
    adjusterName: '박지호',
    resolvedAt: '2026-02-15',
  },
];

export const mockQuotes: Quote[] = [
  {
    id: '1',
    caseId: 'case-1',
    adjusterId: '1',
    adjuster: mockAdjusters[0],
    estimatedAmount: '3,500만원 ~ 4,200만원',
    description: '후유장해 등급 및 일실수입 포함 적극적 청구 가능합니다.',
    timeline: '약 6-8주',
    status: 'pending',
    createdAt: '2026-04-01',
  },
  {
    id: '2',
    caseId: 'case-1',
    adjusterId: '2',
    adjuster: mockAdjusters[1],
    estimatedAmount: '2,800만원 ~ 3,600만원',
    description: '보험사 협상 전문가로서 신속한 합의 도출 가능합니다.',
    timeline: '약 4-5주',
    status: 'pending',
    createdAt: '2026-04-01',
  },
  {
    id: '3',
    caseId: 'case-1',
    adjusterId: '3',
    adjuster: mockAdjusters[2],
    estimatedAmount: '4,000만원 ~ 5,000만원',
    description: '의료 소견서 분석을 통해 최대 청구액 산정하겠습니다.',
    timeline: '약 8-10주',
    status: 'pending',
    createdAt: '2026-04-02',
  },
];

export const mockMessages: Message[] = [
  {
    id: '1',
    chatRoomId: 'room-1',
    senderId: '1',
    content: '안녕하세요! 사건 검토해보았습니다. 자세한 내용 여쭤봐도 될까요?',
    createdAt: '2026-04-03T09:00:00',
    read: true,
  },
  {
    id: '2',
    chatRoomId: 'room-1',
    senderId: 'customer-1',
    content: '네 안녕하세요. 사고 당시 상황을 더 설명드릴게요.',
    createdAt: '2026-04-03T09:05:00',
    read: true,
  },
  {
    id: '3',
    chatRoomId: 'room-1',
    senderId: '1',
    content: '사고 당시 진단서와 치료비 영수증을 보내주실 수 있나요?',
    createdAt: '2026-04-03T09:10:00',
    read: false,
  },
];
